#!/bin/bash
set -eu
VERSION="2.5.0"
rm -rf mongo-c-driver
git clone git@github.com:mongodb/mongo-c-driver.git
pushd mongo-c-driver
git checkout $VERSION
mkdir cmake-build && cd cmake-build
cmake -DENABLE_MONGOC=OFF ..
popd
rm -r bsonjs/bson
rm -r bsonjs/jsonsl
rm -r bsonjs/common
rsync -r mongo-c-driver/src/libbson/src/bson/*.[hc] bsonjs/bson/
rsync -r mongo-c-driver/src/libbson/src/jsonsl/*.[hc] bsonjs/jsonsl/
rsync -r mongo-c-driver/src/libbson/src/jsonsl/LICENSE bsonjs/jsonsl/

rsync -r mongo-c-driver/src/common/src/*.[hc] bsonjs/common/
rsync -r mongo-c-driver/cmake-build/src/common/src/*.[hc] bsonjs/common/
mkdir -p bsonjs/common/mlib
rsync -r mongo-c-driver/src/common/src/mlib/*.h mongo-c-driver/src/common/src/mlib/*.th bsonjs/common/mlib/

rsync -r mongo-c-driver/cmake-build/src/libbson/src/bson/*.[hc] bsonjs/bson/

# Drop implementations for libbson features bsonjs doesn't use and that
# nothing else in the vendored tree calls into (BCON, MD5, the thread
# helpers). Their headers stay: bson.h includes bson-bcon.h, and
# common-thread-private.h is a real dependency of bson-context.c and
# common-b64.c.
rm -f bsonjs/bson/bson-bcon.c
rm -f bsonjs/common/common-md5.c
rm -f bsonjs/common/common-thread.c

# Ignore autogenerated config.h and common-config.h
git diff -- bsonjs/bson/config.h | tee
echo "**** Review libbson's autogenerated src/bson/config.h (above) for newly added (or removed) macros ****"
git checkout -- bsonjs/bson/config.h

git diff -- bsonjs/common/common-config.h | tee
echo "**** Review libbson's autogenerated src/common/common-config.h (above) for newly added (or removed) macros ****"
git checkout -- bsonjs/common/common-config.h
